apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-cluster-flow-server
  namespace: skoala-system
  labels:
    app.kubernetes.io/name: sentinel-cluster-flow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sentinel-cluster-flow-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sentinel-cluster-flow-server
    spec:
      containers:
        - name: sentinel-cluster-flow-server
          image: release-ci.daocloud.io/skoala/sentinel-cluster-flow-server:v0.1.0
          env:
            - name: JAVA_OPTS
              value: -Dnacos.address=nacos-jia.skoala-jia:8848
          ports:
            - name: http
              containerPort: 18730
              protocol: TCP
          resources:
            limits:
              cpu: 1024m
              memory: 1Gi
            requests:
              cpu: 1024m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-cluster-flow-server
  namespace: skoala-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: sentinel-cluster-flow-server
  ports:
    - name: http
      protocol: TCP
      port: 18730
      targetPort: 18730
